(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'7884dbf6-3b29-49da-9080-a231eb774f85-map-container',
          componentName:'MapRaw4',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"isPublishMode":true,"lat":"51.15298199999999","lon":"71.4682189","address":"г. Нур-Султан, ул. Сатпаева 4, ориентир","type":"google","isEditMode":false,"zoom":14,"env":"production","mapboxAccessToken":"pk.eyJ1IjoiZ29kYWRkeSIsImEiOiJjaWc5b20wcjcwczAydGFsdGxvamdvYnV0In0.JK9HuO6nAzc8BnMv6W7NBQ","mapboxStyleUrl":"mapbox:\u002F\u002Fstyles\u002Fgodaddy\u002Fciovyeygh0029atm6zbntgxk2","staticContent":{"today":"сегодня","submitButtonLoadingLabel":"Отправляется","contactFormResponseErrorMessage":"Возникла проблема при отправке вам сообщения. Повторите попытку","defaultCancelButtonLabel":"Отмена","byAppointment":"По договоренности","defaultSubmitButtonLabel":"Отправить","closed":"Закрыто","termsOfSerivce":"Условия обслуживания","recaptchaDisclosure":"Это сайт защищен ключом reCAPTCHA, а также нормативными документами {privacyPolicy} и {termsOfSerivce} Google.","emailValidationErrorMessage":"Введите действительный адрес электронной почты.","mapCTA":"Получить инструкции","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Заполните это обязательное поле","openToday":"Открыто сегодня","privacyPolicy":"Политика конфиденциальности","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms"},"viewDevice":null,"dimensions":{"height":300,"width":375},"widgetId":"7884dbf6-3b29-49da-9080-a231eb774f85","section":"default","category":"accent","locale":"ru-RU","renderMode":"PUBLISH"},{"widgetId":"7884dbf6-3b29-49da-9080-a231eb774f85","widgetType":"CONTACT","widgetPreset":"contact4","order":2,"section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Map","groupType":"Default"});