(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-9',
          componentName:'MessageInvoker',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"config":{"formSubmitEndpoint":"\u002Fmessaging","formSubmitHost":"https:\u002F\u002Fcontact.apps-api.instantpage.secureserver.net","generateUrlHost":"https:\u002F\u002Furl-generator.apps.secureserver.net"},"preset":"messaging1","order":0,"id":"ce6086aa-44f8-4772-bcac-d4154b718213","env":"production","isMobile":null,"websiteId":"f086f545-dfcc-4c44-9bc9-1dccdae9c9c1","accountId":"eb777682-9b68-11ea-81cd-3417ebe725e0","domainName":"test.godaddysites.com","staticContent":{"submitButtonLoadingLabel":"Отправляется","contactFormResponseErrorMessage":"Возникла проблема при отправке вам сообщения. Повторите попытку","defaultCancelButtonLabel":"Отмена","defaultSubmitButtonLabel":"Отправить","endOfChat":"конец беседы","termsOfSerivce":"Условия обслуживания","recaptchaDisclosure":"Это сайт защищен ключом reCAPTCHA, а также нормативными документами {privacyPolicy} и {termsOfSerivce} Google.","emailValidationErrorMessage":"Введите действительный адрес электронной почты.","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Заполните это обязательное поле","privacyPolicy":"Политики конфиденциальности","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms"},"businessName":"ТЕст","emailConfirmationMessage":"Мы отправили вам письмо, нажмите приведенную в нем ссылку, чтобы подтвердить свой адрес.","recaptchaType":"V3","emailOptInHidden":false,"formFields":[{"type":"SINGLE_LINE","label":"Имя","required":false},{"type":"EMAIL","label":"электронную почту","validation":"email","required":true,"replyTo":true},{"type":"SINGLE_LINE","label":"Тел.","required":false},{"type":"MULTI_LINE","label":"Какая вам нужна помощь?","required":false},{"type":"SUBMIT","label":"Отправить сообщение"}],"formEmail":null,"welcomeMessage":"Здравствуйте! Сообщите, чем мы можем вам помочь, и мы ответим в кратчайшие сроки.","formSuccessMessage":"Спасибо за сообщение. Мы ответим вам по электронной почте в ближайшее время.","emailOptInEnabled":false,"emailOptInMessage":"Подпишитесь на получение рассылок с новостями, объявлениями и не только.","widgetId":"ce6086aa-44f8-4772-bcac-d4154b718213","section":"default","category":"accent","locale":"ru-RU","renderMode":"PUBLISH"},{"widgetId":"ce6086aa-44f8-4772-bcac-d4154b718213","widgetType":"MESSAGING","widgetPreset":"messaging1","section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate"});