(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-8',
          componentName:'ContactFormHours',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"structuredHours":[{"hour":{"day":"понедельник","dayOfWeek":1,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"вторник","dayOfWeek":2,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"среда","dayOfWeek":3,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"четверг","dayOfWeek":4,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"пятница","dayOfWeek":5,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":false}},{"hour":{"day":"суббота","dayOfWeek":6,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":true}},{"hour":{"day":"воскресенье","dayOfWeek":0,"openTime":"09:00","closeTime":"17:00","byAppointmentOnly":false,"closed":true}}],"staticContent":{"today":"сегодня","submitButtonLoadingLabel":"Отправляется","contactFormResponseErrorMessage":"Возникла проблема при отправке вам сообщения. Повторите попытку","defaultCancelButtonLabel":"Отмена","byAppointment":"По договоренности","defaultSubmitButtonLabel":"Отправить","closed":"Закрыто","termsOfSerivce":"Условия обслуживания","recaptchaDisclosure":"Это сайт защищен ключом reCAPTCHA, а также нормативными документами {privacyPolicy} и {termsOfSerivce} Google.","emailValidationErrorMessage":"Введите действительный адрес электронной почты.","mapCTA":"Получить инструкции","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Заполните это обязательное поле","openToday":"Открыто сегодня","privacyPolicy":"Политика конфиденциальности","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms"},"collapsible":true,"widgetId":"7884dbf6-3b29-49da-9080-a231eb774f85","section":"default","category":"accent","locale":"ru-RU","renderMode":"PUBLISH"},{"widgetId":"7884dbf6-3b29-49da-9080-a231eb774f85","widgetType":"CONTACT","widgetPreset":"contact4","order":2,"section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default"});