(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'7884dbf6-3b29-49da-9080-a231eb774f85-bootstrap-container',
          componentName:'ContactForm4',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"formTitle":"Ждём вас)","formFields":[{"type":"SINGLE_LINE","label":"Тема","required":false},{"type":"EMAIL","label":"Электронная почта","validation":"email","required":true,"replyTo":true},{"type":"MULTI_LINE","label":"Сообщение","required":false},{"type":"SUBMIT","label":"Отправить","required":false}],"blankInfo":false,"formSubmitHost":"https:\u002F\u002Fcontact.apps-api.instantpage.secureserver.net","showMap":true,"recaptchaEnabled":true,"recaptchaType":"V3","domainName":"test.godaddysites.com","formSuccessMessage":"Спасибо, что оставили запрос! Мы свяжемся с вами в течение 48 часов.","formEnabled":true,"websiteId":"f086f545-dfcc-4c44-9bc9-1dccdae9c9c1","pageId":"0c6533ae-63c5-4350-83b6-31cecd7f6335","accountId":"eb777682-9b68-11ea-81cd-3417ebe725e0","staticContent":{"today":"сегодня","submitButtonLoadingLabel":"Отправляется","contactFormResponseErrorMessage":"Возникла проблема при отправке вам сообщения. Повторите попытку","defaultCancelButtonLabel":"Отмена","byAppointment":"По договоренности","defaultSubmitButtonLabel":"Отправить","closed":"Закрыто","termsOfSerivce":"Условия обслуживания","recaptchaDisclosure":"Это сайт защищен ключом reCAPTCHA, а также нормативными документами {privacyPolicy} и {termsOfSerivce} Google.","emailValidationErrorMessage":"Введите действительный адрес электронной почты.","mapCTA":"Получить инструкции","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Заполните это обязательное поле","openToday":"Открыто сегодня","privacyPolicy":"Политика конфиденциальности","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms"},"emailOptInEnabled":false,"emailOptInHidden":false,"emailOptInMessage":"Подпишитесь на наши почтовые рассылки, чтобы получать обновления, уведомления об акциях и т. п.","emailConfirmationMessage":"Мы отправили вам письмо, нажмите приведенную в нем ссылку, чтобы подтвердить свой адрес.","infoTitle":"","info":"Мы любим наших клиентов, поэтому мы всегда будем рады вашим визитам в рабочее время.","widgetId":"7884dbf6-3b29-49da-9080-a231eb774f85","section":"default","category":"accent","locale":"ru-RU","renderMode":"PUBLISH"},{"widgetId":"7884dbf6-3b29-49da-9080-a231eb774f85","widgetType":"CONTACT","widgetPreset":"contact4","order":2,"section":"default","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default"});